### ISSUE TITLE
Accessibility tests

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [rodrigoprestesmachado/cooperative-editor#29]
Based on Luís' feedback (04/06/2018)

- When the user use one shortcut to jump to a region, we need to create some feedback that the action occurred

- Cut the time and tick information from Sound Chat

- Change the start and end participation sounds to a shorter sounds

- Shortcuts improvements
  - Alt + number[1..9]: move through regions
  - Shift + number[1..9]: describe the screen 
  - Ctrl + number[1..9]: read the messages from Sound Chat

**Comment by rodrigoprestesmachado** [comment]
- Try to spatialise TTS

**Comment by rodrigoprestesmachado** [comment]
New shortcuts:

- Crtl + 1 - Move the cursor to the participants area
- Crtl + 2 - Move the cursor to the chat
- Crtl + 3 - Move the cursor to the editor area
- Shift + 1 - Describe the status of participants
- Shift + 1 - Describe the status of each rubric
- Alt + number (from 1 to 9) - Read the last messages according to the number entered

**Comment by rodrigoprestesmachado** [comment]
1.	Change the “Participation” string to “rounds”

2.	Change “Rubric” string to “evaluation criterion” 

3.	Change “objective” string to “Goal”

4.	Test if the “goal” area (the production description) was properly informed by a screen reader

5.	Change label in the “other participation button” to inform that the colleague can participate.

6.	Make sure that the produced text is accessible by screen reader. Today, only the first line is accessible

7.	Chance the label “Contribution 1” to “Contribution 1: [Rodrigo]” 

8.	Read the text of each contribution automatically

9.	When the cursor is out of the page, for example, in the address bar, and the user we tries to execute an shortcut, we  should alert the user (stand by)

10.	Increase the volume of the sound files

11.	Change the label in rubric “accepted” to “agreed”

12.	Create a shortcut (Alt + Shift + 3) to read the entire produced text

**Comment by laurocj** [comment]
Review tasks: 4 8 9 10 12

13 - menu navigation

14 - Read text with NVDA in editor area

**Comment by rodrigoprestesmachado** [comment]
I have implemented two more features to increase accessibility:

- 15 - The system sets tabindex="-1" to the others "request participation" button
- 16 -  New awareness element to inform that another user is contributing

**Comment by rodrigoprestesmachado** [comment]
We fix all the comments to create the 0.2.0 version
